version: '3'
services:
  node:
    build: .
    ports:
      - 3001:3000
    volumes:
      - src:/src
  centos:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        TEST1: "world4"
    environment:
      TEST2: "world5"
  nginx:
    image: "nginx:latest"
    ports:
      - 80:80
      - 443:443
volumes:
  src:
