version: '3'
services:
  node:
    build: .
    ports:
      - 3001:3000
    volumes:
      - "./src:/src"
    links:
      - nginx
  nginx:
    image: "nginx:latest"
    ports:
      - 80:80
      - 443:443
